spring:
  config:
    import: http://localhost:8088/config #config server 주소
  cloud:
    config:
      fail-fast: true
      allow-override: true
      username: user
      password: user #login info

server:
  port: 8089

#eureka
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: '' #eureka server 주소

